name: Test

on:
  push:
    branches:    
      - 'main'

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - name: Run app and tests
        run: |
          npm start &
          sleep 5
          npm test